# Generated by Django 2.0.4 on 2018-12-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20181214_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='lng',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
