# Generated by Django 2.0.4 on 2018-12-20 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_tarea_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='usuario',
        ),
    ]
